import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // ✅ Fuerza “light” a nivel navegador (ayuda mucho en móviles con dark mode)
  other: {
    "color-scheme": "light",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      // ✅ si por alguna razón Tailwind dark por class se activa, esto ayuda a evitarlo
      className="light"
      // ✅ fuerza scheme light para inputs/selects en varios navegadores
      style={{ colorScheme: "light" }}
    >
      <head>
        {/* ✅ refuerzo extra (algunos navegadores lo respetan más así) */}
        <meta name="color-scheme" content="light" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-slate-900`}>
        {children}
      </body>
    </html>
  );
}